### PR TITLE
Adds `apiKey` to parameters list, fixes broken API calls.

### PR DESCRIPTION
**Pull request by lacymorrow**
Noticed it was broken, hope this helps fix!

Used within lacymorrow/cinematic.

### CODE REVIEW

**Comment by lacymorrow** [comment]
What do you think about this PR? Can it be pulled into the codebase?

**Comment by bbraithwaite** [comment]
Sorry for the delay here, I've been very busy recently. Yes of course!

**Comment by lacymorrow** [comment]
Awesome, thank you for helping me get those pulled in! 
Needed to fix some downstream code that broke when the API began requiring keys by updating this package.

Users will need secure API keys from omdb and update their code to include those keys.

I would recommend a major version bump, as older versions not using an api key should now be

**Comment by lacymorrow** [comment]
Will be closing lacymorrow/ombd-client fork as the npm libs are registered and pulled into the downstream code.

**Comment by lacymorrow** [comment]
Excellent! Thanks for this, I'm going to be pulling this into downstream code after it's registered with npm and removing my fork `lacymorrow/lacymorrow-omdb-client` :)

**Comment by lacymorrow** [comment]
Thanks so much for the merge! 
Let me know when you bump the version and re-publish to npmJS.org, I'll delete my fork and pull your library back into my project `lacymorrow/cinematic`.

Cheers!

**Pull request merged**
